### ISSUE TITLE
CSV for laravel5 ?

### ISSUE THREAD

**Issue by Punksolid** [mnshankar/csv#15]
I think it would be great, because it is the easiest vendor around to export.

Thank you

**Comment by mnshankar** [comment]
CSV should work fine with laravel 5.. It has no dependencies on laravel.. so just add the usual provider and alias entry and you should be good to go.

**Comment by madmanlear** [comment]
For me CSV works out of the box for Laravel 5 except for the need to remove this line from CSVServiceProvider.php:

~~~php
$this->package('mnshankar/CSV');
~~~

Without that change an exception is thrown:

~~~
BadMethodCallException in ServiceProvider.php line 234:
Call to undefined method [package]
~~~

**Comment by ubaidseth** [comment]
I tried madmanlear's suggestion and it still didn't work for me.
